In [1]:
import numpy as np

In [5]:
# How many ways can 1, 3, and 4 add up to a number n. Order matters.

def sum_to_n(n):
    """
    Recurrence: D[n] = D[n-1] + D[n-3] + D[n-4]
    
    Base: D[0] = D[1] = D[2] = 1, D[3] = 2
    """
    D = np.zeros(n)
    D[0] = D[1] = D[2] = 1
    D[3] = 2
    for i in range(4,n):
        D[i] = D[i-1] + D[i-3] + D[i-4]
    return D

In [6]:
sum_to_n(10)

array([ 1.,  1.,  1.,  2.,  4.,  6.,  9., 15., 25., 40.])

In [13]:
# What is the minimum number of steps to get from n to 1.
# Allowed operations are x-1, x/2, and x/3

def number_of_steps_to_one(n):
    """
    Recurrence: D[n] = 1 + min(D[n-1], D[n/2], D[n/3]) when n/2 and n/3 are int
    
    Base: D[1] = 0, D[2] = 1, D[3] = 1
    """
    D = np.zeros(n+1)
    D[1] = 0
    D[2] = 1
    D[3] = 1
    for i in range(4,n+1):
        D[i] = 1 + D[i-1]
        if i % 2 == 0:
            D[i] = min(D[i], 1 + D[i//2])
        if i % 3 == 0:
            D[i] = min(D[i], 1 + D[i//3])
    return D

In [28]:
print(number_of_steps_to_one(15))

[0. 0. 1. 1. 2. 3. 2. 3. 3. 2. 3. 4. 3. 4. 4. 4.]


In [24]:
def number_of_steps_to_one_memo(n):
    memo = np.zeros(n+1) - 1
    def do_it(n):
        if n == 1:
            memo[n] = 0
            return 0
        if memo[n] != -1:
            return memo[n]
        r = 1 + do_it(n - 1)
        if n % 2 == 0:
            r = min(r, 1 + do_it(n//2))
        if n % 3 == 0:
            r = min(r, 1 + do_it(n//3))
        memo[n] = r
        return r
    do_it(n)
    return memo
    

In [27]:
print(number_of_steps_to_one_memo(15))

[-1.  0.  1.  1.  2.  3.  2.  3.  3.  2.  3.  4.  3.  4.  4.  4.]


In [55]:
def fib(n):
    assert n > 0
    memo = np.zeros(n+1)
    def get_fib(n):
        if n == 1:
            memo[n] = 1
            return 1
        if n == 2:
            memo[n] = 1
            return 1
        if memo[n] > 0:
            return memo[n]
        fib = get_fib(n-1) + get_fib(n-2)
        memo[n] = fib
        return fib
    get_fib(n)
    return memo

In [57]:
fib(10)

array([ 0.,  1.,  1.,  2.,  3.,  5.,  8., 13., 21., 34., 55.])